numeric_vector<-c(1.5,2.7,3.2,4.9)
character_vector<-c("Apple","Banana","Cherry","dates")
logic_vector<-c(TRUE,FALSE,TRUE,FALSE)
cat("Numeric vector:\n")
print(numeric_vector)
cat("Charachter Vector:\n")
print(character_vector)
cat("Logical vector :\n")
print(logic_vector)